---
services:
  fastapi:
    container_name: fastapi
    build:
      context: ./
      dockerfile: Dockerfile
    #command: fastapi dev main.py --host 0.0.0.0 --port 8000  
    volumes:
      - ./src:/home/uv-example-user/src
    ports:
      - 8000:8000
    healthcheck:
      test: ["CMD", "curl", "-f", "localhost:8000/healthcheck"]
      interval: 30s
      timeout: 5s
      retries: 5